name: Run Android Emulator and Tests

on:
 pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: '11'

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libx11-dev  # Install missing library for emulator

      - name: Set up Android SDK
        uses: actions/setup-android@v3
        with:
          api-level: 30
          build-tools: 30.0.3
          target: google_apis

      - name: Start Android Emulator
        run: |
          # Create and start the Android Emulator
          echo "Starting Android Emulator..."
          emulator -avd <your-avd-name> -no-window -gpu off -noaudio -no-boot-anim &
          adb wait-for-device
          
          # Wait for the emulator to fully boot
          while [[ "$(adb shell getprop sys.boot_completed | tr -d '\r')" != "1" ]]; do
            sleep 10
            echo "Waiting for emulator to fully boot..."
          done
          sleep 30  # Additional time to ensure the emulator is stable

      - name: Run Flutter integration tests
        run: |
          echo "Running Flutter integration tests..."
          flutter test integration_test --dart-define=CI=true --no-android-reset --machine > test-results.json

      - name: Upload test results
        uses: actions/upload-artifact@v4
        with:
          name: test-results
          path: test-results.json

      - name: Clean up emulator
        run: |
          echo "Shutting down the emulator..."
          adb emu kill
